server:
  port: 8001

mybatis:
  # mybatis配置文件所在路径  config-location: classpath:mybatis/mybatis.cfg.xml
  # 所有Entity别名类所在包
  type-aliases-package: ccom.sitech.springcloud.entities
  # mapper映射文件
  mapper-locations:  - classpath:mybatis/mapper/**/*.xml
  
spring:  application:    name: microservicecloud-dept  datasource:
    # 当前数据源操作类型    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包    driver-class-name: org.gjt.mm.mysql.Driver
    # 数据库名称 jdbc:mysql://ip:端口号/库名
    url: jdbc:mysql://192.168.1.111:3306/dawei_01
    username: dawei_sql
    password: 111111
    dbcp2:
      # 数据库连接池的最小维持连接数      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-idle: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200
      
eureka:  client:    service-url:
      # 单机版      #defaultZone: http://localhost:7001/eureka/
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # 修改注册中心的status    instance-id: microservicecloud-dept8001-hystrix
    # 访问路径可以显示Ip地址
    prefer-ip-address: true
    
info:
  app.name: microservicecloud-dept
  company.name: www.sitech.com.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$  